
# https://aka.ms/yaml
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  mavenVersion: '3.8.4'
  javaVersion: '17'

steps:
  - task: JavaToolInstaller@0 
    inputs:
      versionSpec: $(javaVersion)
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled' 

  - task: Maven@4
    inputs:
      mavenVersionOption: 'Default'
      mavenPomFile: 'asdchai/pom.xml'
      goals: 'clean install'
      options: '-DskipTests'

  - task: Maven@4
    displayName: 'Run JavaFX Application'
    inputs:
      mavenPomFile: 'asdchai/pom.xml'
      goals: 'javafx:run'
      options: '-Djavafx.platform=win'
